### ISSUE TITLE
No wiki?

### ISSUE THREAD

**Issue by Isaac96** [andrewrapp/arduino-sketcher#1]
Could you make a wiki? 
I can't understand all your awesome work! :disappointed: :

**Comment by Isaac96** [comment]
OOPS
Just saw your link :smiley:

**Comment by andrewrapp** [comment]
I will move the documentation to the wiki, if there's sufficient interest in the project, but for now it's on Medium

**Comment by Isaac96** [comment]
Having everything on GitHub makes it easier to read the docs.
